class TestError(Exception):
    print('TestError raised')
    pass
